module.exports = {
    BOOKING_CREATED: "BOOKING_CREATED",
    BOOKING_APPROVED: "BOOKING_APPROVED",
    BOOKING_REJECTED: "BOOKING_REJECTED",
    BOOKING_CANCELLED: "BOOKING_CANCELLED",
    BOOKING_RETURNED: "BOOKING_RETURNED",
};
